### ISSUE TITLE
Question on Gitea for Synology

### ISSUE THREAD

**Issue by ghost** [wkobiela/Jenkins#3]
Sorry to bother you in this repo but I do not know how to contact you. Seems there is no GitHub internal messageboard.

Running your Gitea package on Synology which is great !!!!
Are you planning to get new version out? Last week Gitea version 18.0 was released and would be great if that version comes to Synology.

Regards,
Dave

**Comment by wkobiela** [comment]
Hi Dave,
I've sold my Synology server some time ago, so I'm not using Gitea package anymore. Nevertheless updating packate is pretty straight forward. You could try to use my simple python project https://github.com/wkobiela/GiteaReleaseGetter

It is basically updating whole neccessary files for Gitea package and pushing it to your spksrc fork. Only manual step is to create pull request to SynoCommunity spksrc repository :)
